spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT:3306}/${DB_NAME}?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=Asia/Shanghai
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
  h2.console.enabled: false
springdoc:
  api-docs.enabled: false
  swagger-ui.enabled: false
app:
  storage.type: s3
  realtime.mode: redis
management:
  endpoint:
    health:
      show-details: never
